language: python

os: linux

python:
    - "3.6"

env:
    matrix:
        - TESTENV=docs
        - TESTENV=code
        - TESTENV=pylint

# command to install dependencies
install:
    - pip install .
    - pip install -r requirements.txt
    - if [[ "$TESTENV" == "docs" ]]; then pip install sphinx;fi
    - if [[ "$TESTENV" == "pylint" ]]; then pip install pylint;fi

# command to run tests
script:
    - if [[ "$TESTENV" == "docs" ]]; then ./scripts/travis/docs_harness.sh; fi
    - if [[ "$TESTENV" == "pylint" ]]; then ./scripts/travis/pylint_harness.sh; fi
